### ISSUE TITLE
[FR] Add deletion variants of command

### ISSUE THREAD

**Issue by huyz** [bysreg/horizontal-jump#8]
Left and Right.

Sometimes I just want to delete a really long string of text, regardless of regular "word boundaries"; whitespace is what matters.

**Comment by hbeyri** [comment]
I think this would already be covered by the new "select right" and "select left" command recently released in 1.0.2 ([779524d](https://github.com/bysreg/horizontal-jump/commit/779524d2b461e2abe6ba60423a5b8edfc22200d3)). You'd need to just press an extra keypress of delete.
